services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "${LANGFLOW_PORT:-7860}:${LANGFLOW_PORT:-7860}"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=${LANGFLOW_DATABASE_URL:-postgresql://langflow:langflow@postgres:5432/langflow}
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      # - LANGFLOW_CONFIG_DIR=app/langflow
      - LANGFLOW_PORT=${LANGFLOW_PORT:-7860}
    volumes:
      - langflow-data:/app/langflow

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-langflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-langflow}
      POSTGRES_DB: ${POSTGRES_DB:-langflow}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:
